CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

INSERT INTO users (username, password)
VALUES ('test', '$2y$10$EL4NPlJ4u8BUPIdXN0EDMO7XnHPKI502YiC2CbECKGypC.ul1RMna');
