version: '3.8'

services:
  apache-php:
    container_name: apache_php
    build: ./apache-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache-php/src:/var/www/html
      - ./apache-php/logs:/var/logs/apache2
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - servers_net

  mysql:
    container_name: mysql_server
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "secure_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-logs:/var/log/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - servers_net
    command: --local-infile=1 --secure-file-priv=/var/lib/mysql-files

volumes:
  mysql_data:

networks:
  servers_net:
    driver: bridge
