version: "3.8"

services:
  apache-php:
    container_name: apache_php
    build: ./apache-php
    ports:
      - "80:80" # HTTP apenas, sem HTTPS
    volumes:
      - ./apache-php/src:/var/www/html # Código da aplicação
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - servers_net
    environment:
      - PHP_DISPLAY_ERRORS=1 # Mostrar erros no navegador
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_ALLOW_URL_FOPEN=1 # Permitir fopen remoto

  mysql:
    container_name: mysql_server
    image: mysql:5.6 # Versão antiga e insegura
    environment:
      MYSQL_ROOT_PASSWORD: "root" # Senha fraca
      MYSQL_DATABASE: "secure_db"
      MYSQL_USER: "secure_user"
      MYSQL_PASSWORD: "password" # Senha comum
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - honeypot_net
    command: --local-infile=1 --secure-file-priv=/tmp # Configuração insegura

volumes:
  mysql_data:

networks:
  servers_net:
    driver: bridge
