version: '3.8'

services:
  apache-php:
    container_name: apache_php
    build: ./apache-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache-php/src:/var/www/html
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - servers_net

  mysql:
    container_name: mysql_server
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "T3stR0Ot@10"
      MYSQL_DATABASE: "secure_db"
      MYSQL_USER: "secure_user"
      MYSQL_PASSWORD: "T3stU5r@11"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - servers_net

volumes:
  mysql_data:

networks:
  servers_net:
    driver: bridge
